### ISSUE TITLE
Kafka appender infinite loop ?

### ISSUE THREAD

**Issue by Jacuo** [danielwegener/logback-kafka-appender#45] opened 2017-03-10 11:44 UTC
I tried to use Kafka Appender with spring boot / spring cloud application with kafka client 0.10.11 . There was error during startup `org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.`, which caused app to hang. I supposed, that there is problem of sending messages from kafka itself.  I  changed logback-spring.xml 
```
	<logger name="kafka" additivity="false">
		<appender-ref ref="STDOUT" />
	</logger>
	<root level="info">
		<appender-ref ref="STDOUT" />
		<appender-ref ref="kafka-appender" />
	</root>
```
This workaround works, but messages from kafka are not sent to Kafka. Is it possible to fix this problem ?

**Comment by danielwegener** [comment] 2017-03-13 19:35
Thanks for the report. Sounds like a duplicate of #33.

**Closed by danielwegener** 2017-03-13 19:35 UTC
