### ISSUE TITLE
Messages being dropped by async delivery and not going to fallback appender

### ISSUE THREAD

**Issue by khampson** [danielwegener/logback-kafka-appender#14] opened 2015-10-29 21:19 UTC
Hi:

I have been experimenting with **logback-kafka-appender** in order to pipe messages from an app into our Kafka cluster. I am using *AsynchronousDeliveryStrategy*, and I've noticed when cross-checking the output that I've redirected from STDOUT into a local log file that some messages are missing versus what I ultimately get back out of Kafka (using the **kafka-console-consumer.sh** script that ships with the Kafka binaries).

I was somewhat surprised, as while the volume isn't small, I wouldn't consider it huge on a big-data scale (roughly 61000 messages delivered over the course of 2 minutes, some at faster bursts than others). I've tried tweaking various settings (**linger.ms**, the batch size, the retries, etc.) and it doesn't appear to have an effect.

I figured I would then implement a fallback appender which would write to its own log file, which I could then push into Kafka at the app's end as a backfill. However, the log for the appender ends up being a 0-byte file. I attached to the app remotely via the Eclipse debugger, and set breakpoints on the places where **onFailedDelivery** is called, and did not hit any of them. I also profiled the code and did not see any relevant exceptions thrown.

I've tried the **BlockingDeliveryStrategy**, and while all the messages were delivered, it ended up causing a near doubling of the runtime of the app, so that really isn't an option. If the fallback appender could work, I am fine with that, but currently I seem to be at a crossroads where messages seem to be disappearing without fallback.

Have you seen anything like this? Is there anything you would suggest I try? I'm pasting in my **logback.xml** below (Github won't let me attach it as an xml nor a txt file).

Thanks!

-- Ken

    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>[[app]] %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
      </appender>

      <appender name="kafkaFallbackFileAppender" class="ch.qos.logback.core.FileAppender">
        <file>kafka_fallback.log</file>

        
        <append>false</append>

        
        <encoder>
          <pattern>[[app]] %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
      </appender>

      <appender name="kafkaAppender" class="com.github.danielwegener.logback.kafka.KafkaAppender">
                
                <encoder class="com.github.danielwegener.logback.kafka.encoding.PatternLayoutKafkaMessageEncoder">
                    <layout class="ch.qos.logback.classic.PatternLayout">
                        <pattern>[[app]] %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg</pattern>
                    </layout>
                </encoder>

                <topic>logger-dev</topic>

                <keyingStrategy class="com.github.danielwegener.logback.kafka.keying.RoundRobinKeyingStrategy" />

                <deliveryStrategy class="com.github.danielwegener.logback.kafka.delivery.AsynchronousDeliveryStrategy" />

                
                
                
                <producerConfig>bootstrap.servers=kafka:9092</producerConfig>

                <producerConfig>acks=all</producerConfig>

                <producerConfig>block.on.buffer.full=true</producerConfig>

                <producerConfig>buffer.memory=268435456</producerConfig>

            <producerConfig>retries=3</producerConfig>

            <producerConfig>batch.size=32768</producerConfig>

            
                <appender-ref ref="kafkaFallbackFileAppender"/>
     </appender>

      <root level="INFO">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="kafkaAppender" />
      </root>
    </configuration>

**Comment by danielwegener** [comment] 2015-11-02 18:32
Hey Ken,

I have tried to toy around with your settings and dived through the kafka documentation and cannot really see where the behaviour is coming from (even tried to reproduce the behaviour with integration tests - but a million messages go through different combinations of broker count, partition count and replication factor without any problems and without a single lost message).

Do the kafka server logs tell anything unusual? Can you tell a bit more about your server configuration (broker count, max request size, replication factor, partition count and so on?)

Kind regards

**Comment by khampson** [comment] 2015-11-03 21:56
Hi, Daniel:

Thanks for investigating. I'm in the beginning phases of setting up centralized logging with Kafka, so currently I am using a topic with a partition count of 3 and replication factor of 3; with 3 brokers. I currently do not have any other settings specified (based on the ones shown in "Update Config" in the Kafka Manager UI), so I should have the defaults in terms of max request size and such.

I took a look in the logs, and I do see some instances of exceptions that suggest some connectivity issues, e.g.

java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at kafka.utils.Utils$.read(Utils.scala:380)
        at kafka.network.BoundedByteBufferReceive.readFrom(BoundedByteBufferReceive.scala:54)
        at kafka.network.Processor.read(SocketServer.scala:444)
        at kafka.network.Processor.run(SocketServer.scala:340)
        at java.lang.Thread.run(Thread.java:745)

But there doesn't seem to be anything close to a 1:1 correlation. (I just re-ran the test this afternoon, and didn't see any of these exceptions in the Kafka server logs, but when I compare the the local log with the consumed output from the Kafka topic, over 400 messages are missing. The fallback appender's log was again 0 bytes.

Any further suggestions you may have would be appreciated. Thanks!

-- Ken

**Comment by khampson** [comment] 2015-11-05 00:05
Hi, Daniel:

FYI, I continued to investigate this, and I find myself unable to reproduce the issue now after being able to consistently do so for several days. My current theory on this is that it is related to a network infrastructure issue (there have been some changes recently that were reverted that I suspect caused the issue).

I plan to create a test that will run daily and check to make sure no messages are lost, since I think that would really be the only way to tell. (I suspect that these issues were preventing the Kafka server from ever actually seeing the messages, and therefore it didn't get an exception back, and didn't land on the fallback appender).

Is there anything config-wise in the logback.xml that you would suggest that might be able to help with such circumstances? (My attempts at tweaking the settings during the period of time when I could reproduce the issue did not appear to lead to any different behavior.)

Thanks,
-- Ken

**Comment by danielwegener** [comment] 2015-11-05 08:40
Hi @khampson 
Good to known - I was getting crazy about maybe overlooking something :)

It is still a bit weird that you requested `ack=all` and still got no exceptions back from the leading broker that resulted in an append on the fallback appender. I think the ack=all is also a bit dangerous because it might cause that the outage (network partition or maintenance, does not matter) of a single broker could put all your applications on hold. Depending how "important" your logs are, an `ack=2` should be sufficient.

If you want to monitor your sent message count/throughput etc., you can monitor the kafka producer via jmx (see https://kafka.apache.org/documentation.html#monitoring).

One lesson I learned the hard way: make sure that your producers `max.request.size` and `batch.size` to never exceed the values on the broker side - otherwise big messages just get dropped. 

I think it would also be useful to have a "max message size" configuration in logback-kafka-appender that emits warnings if somone tries to log messages that are bigger than the message size that the producer is able to handle.

I'ts also always helpful for debugging purposes to set the `client.id`property to something meaningful when you try to analyze the server logs (I think logback allows you to fill in a $HOSTNAME or some other kind of placeholder there).

Hope that helps :)

Kind regards

**Comment by danielwegener** [comment] 2015-11-06 12:56
@khampson By the way, can we close this issue?

**Comment by khampson** [comment] 2015-11-06 15:45
Hi, Daniel:

Thanks for the suggestions. I will look into the JMX montioring, and heed the warning re: `max.request.size` and `batch.size`. I'll need to think about the `ack` setting, as the logs are quite important (we'll be mining them down the line, and sometimes relying on them for diagnosing problems, among other things), so I'd like to be as sure as possible that nothing got dropped along the way. I'll also look into `client.id` further.

I agree re: having a max size in logback-kafka-appender that emits warnings (or, perhaps even optionally, an exception) would be a good thing.

I believe it should be fine to close this issue. Thanks for investigating and for the suggestions!

-- Ken

**Closed** 2015-11-06 15:45 UTC
